{% set name = "gbquality" %}
{% set version = "0.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3be768a845c8fb56e95feb849dd486b54e2083978ed539199c20f78eb756a56f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.4
    - numba >=0.47.0
  run:
    - numpy
    - python >=3.4
    - scikit-learn
    - scipy
    - numba >=0.47.0

test:
  imports:
    - gbquality

about:
  home: https://github.com/AndLen/gbquality
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python translation of the original MATLAB code for the GB measure.
  dev_url: https://github.com/AndLen/gbquality

extra:
  recipe-maintainers:
    - AndLen
